### ISSUE TITLE
Disable "flip photo" if there's no back

### ISSUE THREAD

**Issue by ryaanahmed** [dhmit/paris_1970#18]

**Comment by ryaanahmed** [comment]
Possibly the more general issue is "handle a variable number of images" -- because we have some images that have been digitized front, back, and in the binder.

**Comment by JasonLin43212** [comment]
If we have a variable number of photos, should we change it so that on the spreadsheet, instead of having a `front_src` and `back_src`, we just have one column `srcs` which is just comma separated sources?

**Comment by ryaanahmed** [comment]
We're coding all of the filenames as `<PHOTO_NUMBER>_front`, `<PHOTO_NUMBER>_back`, `<PHOTO_NUMBER>_binder` at this point, right? I think that means we no longer need to explicitly code `front_src` or `back_src` in our spreadsheet, and instead dynamically set these in `syncdb`.
