### ISSUE TITLE
Sort out 'Photographers' page Layout

### ISSUE THREAD

**Issue by bukunmishodipo** [dhmit/paris_1970#223]
The way the photos are being rendered needs to be fixed. All the photos should be placed in an assets directory and resized to thumbnail size for list display.

- [x] render photos properly by creating a directory for them
- [ ] get layout to match Figma design for the 'Photographers' page
- [ ] get image size and text size to be consistent with what is on the [style guide](https://www.figma.com/file/PLCRwxbiYmdS4T67QzYgP2/Style-Guide?node-id=0%3A1)

**Comment by jeffreyshen19** [comment]
Sounds good! I remember last lab meeting there was confusion over where to find the photos to put in assets. Have you resolved this?
