### ISSUE TITLE
Fix navbar overlapping content

### ISSUE THREAD

**Issue by ryaanahmed** [dhmit/paris_1970#23]
The way the navbar is implemented right now, it cuts off content. We've got a hack-y bit of margin above the topmost element so it's not obscured by the navbar, but we should fix this.

**Comment by JasonLin43212** [comment]
The navbar overlaps the content right now because it has `position:fixed`. If we remove the margin, does that mean that we want a navbar that does not follow the user as they scroll?

**Comment by ryaanahmed** [comment]
> If we remove the margin, does that mean that we want a navbar that does not follow the user as they scroll?

Nope -- my description of the issue above is unclear. The problem isn't that we're setting a margin. The problem is we're setting a margin on a specific element in the content. What we probably want to do is have a content container div that sets whatever margin or padding we need to clear the navbar.
