### ISSUE TITLE
Pickling the Analysis

### ISSUE THREAD

**Issue by JasonLin43212** [dhmit/paris_1970#29]
- Pickle the analysis results and store it in a file.
- When running the analysis, we want to not recompute previously computed results, so we can check the file for the results.
- We can add a flag that tells the program to rerun the analysis for all entries in the database.

**Comment by JasonLin43212** [comment]
We might need to change the structure of the analysis functions and how we use the analysis results. We can add an extra (optional?) argument that says to recompute or not.

If we want to not recompute the results for a specific item, we need to have something that identifies that item. Maybe we can use the primary key in conjunction with the model name to identify a specific item in the pickle file, so we know whether that specific item already has been computed.

**Comment by JasonLin43212** [comment]
Branch: `pickling_analysis`

**Comment by JasonLin43212** [comment]
Another better idea: the `analysis` function will take in one argument, which is a specific object. Inside each of the individual files, we can have a field that has which model we want to do the analysis for. This way, we can do this more generally to any model we want

**Comment by JasonLin43212** [comment]
We can have a folder called `analysis_results` that can store the pickle files for each individual analysis. This way, we don't have to unpickle the results from every analysis just to get the results for one analysis.

**Comment by ryaanahmed** [comment]
This looks like generally a good plan.

My suggestion is that before implementing a more general solution as you propose here, let's wait until we have more than one analysis in the system. That way we can encounter and fix the problems as they arise, rather than trying to predetermine a general solution.

**Comment by ryaanahmed** [comment]
(So, as usual, for now do the simplest version of this that moves us in the right direction, and then we can refactor to accommodate increased complexity.)
