### ISSUE TITLE
Create Some Way for Storing More General Analysis

### ISSUE THREAD

**Issue by JasonLin43212** [dhmit/paris_1970#34]
Currently, we have a system of analysis where we go through all the objects of a certain model, do some analysis, and add the results into the database. We would like to have a more general way to perform analysis so that questions such as "What is the total number of photos?" can be computed and stored in our database.

- One idea that could work is to have a model that stores general analysis results. Its can have fields such as `analysis_name` and `analysis_result`. So, every time we do a more general analysis, we can add in a new object, or edit an already existing one to store the values of the analysis.

- Another weirder idea could be to just have one object in this model that has fields for all general analysis results.

**Comment by ryaanahmed** [comment]
> Another weirder idea could be to just have one object in this model that has fields for all general analysis results.

This is not such a crazy idea! Sometimes these are called "singleton models", where you have a database that's intended to hold only a single record. Often used for things like global settings.

I think for this application, however, this pattern has some downsides -- namely that every additional chunk of data we want to store in the record requires a database migration and rebuild of that record.

I think the first idea makes more sense. If the `analysis_result` field is JSON, then we can store pretty much any data we want. The model can be called something like `CorpusAnalysisResult` to indicate that it saves results that apply over the whole corpus.
