### ISSUE TITLE
Create analysis module to determine if a photo is a portrait

### ISSUE THREAD

**Issue by felixli5678** [dhmit/paris_1970#54]
https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_objdetect/py_face_detection/py_face_detection.html#face-detection

- [ ] Using the haar cascade in OpenCV, we can detect faces in a photo (using their training data) and we can also tell how many faces there are.

- [ ] If an image only has one face, then we can set a certain threshold so that if the area of the face reaches that threshold in the photo we can determine if the image is a "portrait."

**Comment by ryaanahmed** [comment]
This looks like a great first project to me! Go for it.

**Comment by ryaanahmed** [comment]
Closed via #70
