### ISSUE TITLE
Create an analysis module to determine level of detail in photo

### ISSUE THREAD

**Issue by JusticeV452** [dhmit/paris_1970#55]
Determining the level of detail in the photo could help us determine the skill level of the photographer. 
We could possibly accomplish this by:

- Stratifying images based on the number of discrete pixels they contain and ordering them by standard deviation within their stratum.
- Calculating local variance of pixels (numpy might have tools to make this simple).
- Taking a Fourier transform of the images and ordering images based on the magnitude of their highest frequency coefficient (numpy can quickly take the Fourier transform of an image).

@ryaanahmed @clarkce

**Comment by ryaanahmed** [comment]
Looks good to me as a first project! Go for it.

I want to push back against the framing here, though—that is, the idea that we're trying to determine the skill level of the photographer. Let's chat in our Friday session, particularly with @clarkce about this, but have a think about the kinds of parameters that highly skilled photographers might manipulate when composing images. Are skilled photographers always going to produce images that we consider highly detailed, where detail is measured in one of the ways we've outlined here?

**Comment by clarkce** [comment]
I agree with Ryaan here -

here are two images from the collections of the metropolitan museum of art:

https://www.metmuseum.org/art/collection/search/267775?searchField=All&amp;deptids=19&amp;high=on&amp;ft=*&amp;offset=0&amp;rpp=100&amp;pos=61

https://www.metmuseum.org/art/collection/search/265556?searchField=All&amp;deptids=19&amp;high=on&amp;ft=*&amp;offset=0&amp;rpp=100&amp;pos=71

One is very detailed, one is not, both are in an art museum.

In general we want to produce tools that evaluate what is in the image not what we judge the image to be.

All my best,

cc

On Sep 24, 2020, at 8:40 AM, Ryaan Ahmed <notifications@github.com<mailto:notifications@github.com>> wrote:



Looks good to me as a first project! Go for it.

I want to push back against the framing here, though—that is, the idea that we're trying to determine the skill level of the photographer. Let's chat in our Friday session, particularly with @clarkce<https://github.com/clarkce> about this, but have a think about the kinds of parameters that highly skilled photographers might manipulate when composing images. Are skilled photographers always going to produce images that we consider highly detailed, where detail is measured in one of the ways we've outlined here?

**Comment by ryaanahmed** [comment]
closed via #66
