### ISSUE TITLE
Create analysis module to determine foreground, middleground, background of photo

### ISSUE THREAD

**Issue by hilaryzen** [dhmit/paris_1970#56]
- Use the [GrabCut algorithm](https://docs.opencv.org/master/d8/d83/tutorial_py_grabcut.html) to extract the foreground of an image, and identify middleground and background based off our results.

- Use edge detection or contrast detection in different sections of the photo in order to identify the focus of the photo.

- If we have extra time, we plan to work on identifying what the subject of the foreground is with machine learning.

@ryaanahmed @clarkce

**Comment by ryaanahmed** [comment]
This general area of exploration looks good to me, but I'd suggest that we narrow the scope for this first project. 

Producing even a fairly rough estimation of the amount of the image that is in the foreground will already give us a powerful mechanism by which to sort the whole set of photos. My suggestion is to stop there (basically partway through your first bullet point here), at which point we'll have a useful result from this exploration, and then we can regroup and figure out next directions.

**Comment by ryaanahmed** [comment]
Closed by #71
