### ISSUE TITLE
Create analysis function to detecting person density within a photo

### ISSUE THREAD

**Issue by ronaywang** [dhmit/paris_1970#57]
- [ ] We would like to use the OpenCV library haar-cascade (https://docs.opencv.org/master/db/d28/tutorial_cascade_classifier.html) to detect how many people are in a photograph. That way we can figure out which locations are more prone to crowds and which have fewer crowds.

@ryaanahmed @clarkce

**Comment by ryaanahmed** [comment]
Looks like a good first project to me. Please note that #54 is related work, and there might be some reduplication of efforts here that we'll need to factor out later. That's okay with me for this first project, as this kind of face detection is a kind of foundational work.

@felixli5678 @fyang3 @michellejhe -- bringing this issue to your attention so you can all be in touch and share any overlapping code.

**Comment by ryaanahmed** [comment]
closed via #68
