### ISSUE TITLE
Create analysis module to identify if image was captured indoors

### ISSUE THREAD

**Issue by montsegarza** [dhmit/paris_1970#59]
- [ ]  Determine if image is a courtyard image taken through an alleyway by identifying if the border is only dark pixels
- [ ] Determine if image is outdoors by finding buildings in the image using corner and/or edge detection

**Tutorials we plan to use:**
[Harris Corner Detection](https://docs.opencv.org/master/dc/d0d/tutorial_py_features_harris.html)
[Shi-Tomasi Corner Detector](https://docs.opencv.org/master/d4/d8c/tutorial_py_shi_tomasi.html)
[Canny Edge Detection](https://docs.opencv.org/master/da/d22/tutorial_py_canny.html)

**Comment by montsegarza** [comment]
@ryaanahmed @clarkce  Let us know what you think about the scope of this project!

**Comment by ryaanahmed** [comment]
Let's discuss in our call today: recall that the vast majority of the photos from the competition are outdoors. My feeling is that focusing on the building detection part of this project might be more tractable.

**Comment by ryaanahmed** [comment]
Closed via #67
