### ISSUE TITLE
Create analysis module to identify significant lines/vanishing point within photo

### ISSUE THREAD

**Issue by taokinbo** [dhmit/paris_1970#60]
https://docs.opencv.org/master/da/d22/tutorial_py_canny.html
https://docs.opencv.org/master/d6/d10/tutorial_py_houghlines.html

- [ ] Use the canny edge detection to create a binary image 

- [ ] Apply Hough lines transformation to a binary image which will return an array of line data

- [ ] Filter line data to obtain the most 'significant' lines by removing short and parallel lines

- [ ] Create or import algorithm to help determine the intersections of significant lines (vanishing points) 

- [ ] Analysis returns if an image contains a vanishing point and if so, returns the location of the vanishing point. 

@ryaanahmed @clarkce

**Comment by ryaanahmed** [comment]
Looks good to me! @clarkce can confirm but I bet this work could get us towards some interesting ways to filter photos by their composition.

**Comment by ryaanahmed** [comment]
Closed via #74
