### ISSUE TITLE
Create interactive map connecting images to map squares

### ISSUE THREAD

**Issue by RaquelGarcia999** [dhmit/paris_1970#72]
Our team will make an interactive map view so that visitors will be able to click on a square in either the current/historical map and be shown a view of all the images associated with that map square.
Main components:

-[] Original map with distinct squares, squares associated with images we have are highlighted and others are grayed out

-[] New map view using Google Maps API, same functionality as (1) but the squares now indicate the current state of the square, not the historical (We'd have to use coordinates for this.) Add toggle functionality so we can switch between (1) and (2)

-[]  Hover feature- hover over a map square region/coordinate in the maps in (1) or (2) and see information about the photos we have associated with that square, such as the number of photos

-[] Square-specific query to archive- click on a map square region/coordinate in the maps in (1) or (2) and go to a page showing all the photos that are associated with that map square

@ryaanahmed @clarkce

**Comment by ryaanahmed** [comment]
Closed via #92
