### ISSUE TITLE
Visualization of Analysis Data

### ISSUE THREAD

**Issue by taokinbo** [dhmit/paris_1970#81]
Our team will create a widget that will show a visual representation of the data given from numerous analyses. 
Main components:

- [ ] Have the widget be a dropdown menu on the individual picture page

- [ ] Only one analysis will be toggled on at a time

- [ ] Analyses we want to work on displaying are Find Vanishing Point and Foreground Detection. 

@ryaanahmed @clarkce

**Comment by ryaanahmed** [comment]
Closed via #85
