### ISSUE TITLE
Photographer View

### ISSUE THREAD

**Issue by felixli5678** [dhmit/paris_1970#82]
Tasks:
- [x] Fix the current photographer's view. (Jason)
- [x] Add photographer view link in photo view. (Jason)

Things to include in view:
- [ ] Map square of each photographer.
- [ ] Biographical information like location if possible.
- [x] List/gallery of their photos.
- [x] Aggregate/average numerical analysis of their photos.

**Comment by ryaanahmed** [comment]
Closed via #84 -- we can open the bio information stuff as a follow-on issue later if that becomes feasible (still have privacy issues to work out around displaying that information).
